### ISSUE TITLE
Privacy error issue with mkcert

### ISSUE THREAD

**Issue by jp1971** [xwp/vip-go-site#101]
Hello. I am running into an issue with mkcert. 

mkcert installed successfully as did the certificates. Here's the output from the docker container:
```
Created a new certificate valid for the following names 📜
- "local.devgo.vip"
- "*.local.devgo.vip"
Reminder: X.509 wildcards only go one level deep, so this won't match a.b.local.devgo.vip ℹ️
The certificate is at "local.devgo.vip.crt" and the key at "local.devgo.vip.key" ✅
It will expire on 11 June 2023 🗓
Note: the local CA is not installed in the system trust store.
Run "mkcert -install" for certificates to be trusted automatically ⚠️
```
 Chrome is not recognizing the certificate authority - i.e. `NET::ERR_CERT_AUTHORITY_INVALID`

**Comment by jp1971** [comment]
Never mind. I just reread the readme and saws this "The local development environment uses a self-signed SSL sertificate for HTTPS so the "Your connection is not private" error can be ignored to visit the site."

**Comment by kasparsd** [comment]
@jp1971 One way to fix the error is to add the generated CA certificate to your system certificate store. Those certs are unique for each development environment and generated inside the `mkcert` docker container so you would need to map the certificate directory to a local directory instead of a named mount here:

https://github.com/xwp/vip-go-site/blob/97f588f660b7e38e9b98d2d31f06c7eaeba9ff52/docker-compose.yml#L16

And then run `CAROOT=path/to/that/directory mkcert -install` to install the certificates generated in the docker container on your local machine.
