### ISSUE TITLE
Error: Cannot start service wordpress

### ISSUE THREAD

**Issue by mehigh** [xwp/vip-go-site#116]
Creating vip-go-site_wordpress_1 ... error

ERROR: for vip-go-site_wordpress_1  Cannot start service wordpress: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/Users/mike/Sites/test-vip-go/vip-go-site/local/public/wp-cli.yml" to rootfs at "/var/www/html/wp-cli.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for wordpress  Cannot start service wordpress: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/Users/mike/Sites/test-vip-go/vip-go-site/local/public/wp-cli.yml" to rootfs at "/var/www/html/wp-cli.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: Encountered errors while bringing up the project.

OSX Catalina 10.15.7 / Docker 3.4.0 / Node 12.22

**Comment by nandotess** [comment]
I'm having the same issue with this setup:
`OSX Big Sur 11.3 / Docker 3.4.0 / Node 12.22.1`

I will do an investigation to help with this debug and (hopefully) solution...

**Comment by nandotess** [comment]
I have a few notes about this issue. I feel I've found the root cause but I'm not sure yet about the solution to the issue.

![image](https://user-images.githubusercontent.com/804109/122414698-55961100-cf55-11eb-9af5-79968407a79c.png)

As you can see on the image above, there are 3 files that are created as *folders* and not *files* on the `npm run start` script:
- `wp-cli.yml`
- `wp-config.php`
- `object-cache.php`

Other than that, the `object-cache.php` is placed in a different place/folder than informed on the `docker-compose.yml` file: `wp-content/object-cache.php`.

![image](https://user-images.githubusercontent.com/804109/122415363-d8b76700-cf55-11eb-88f3-885df496fb42.png)

If I manually fix this issue (rename 3 files and change the location of the last one), the `npm run start` script works fine.

---

Not quite sure if this is related or not. But after that is manually solved, I'm having a different issue with the *NGINX Proxy* that is reporting *502 Bad Gateway*.

There are no ports conflicts on my localhost or any other Docker instance mounted/running that is not this website.

![image](https://user-images.githubusercontent.com/804109/122415942-51b6be80-cf56-11eb-88a5-72c80603286e.png)

*MailHog* is working fine.

![image](https://user-images.githubusercontent.com/804109/122415995-5ed3ad80-cf56-11eb-820c-be91205c7d4b.png)

I hope these notes can help to find the solution to this bug. :crossed_fingers:

**Comment by kasparsd** [comment]
@nandotess Can you please confirm if you did `npm install` before running `npm run start`?

During the `npm install` it [also runs](https://github.com/xwp/vip-go-site/blob/fe7def340011c9c84d32f5fa102481ddd384dc20/package.json#L7) `composer install` which pulls in `automattic/vip-go-mu-plugins` which provides `plugins/vendor/automattic/vip-go-mu-plugins/drop-ins/object-cache/object-cache.php` which [is mapped to the root of this repository](https://github.com/xwp/vip-go-site/blob/fe7def340011c9c84d32f5fa102481ddd384dc20/docker-compose.yml#L99) in the WP container since that represents the "wp-content" directory (which would contain the drop-ins).

We also map the following files and directories from this file tree to different locations inside the WP container:

https://github.com/xwp/vip-go-site/blob/fe7def340011c9c84d32f5fa102481ddd384dc20/docker-compose.yml#L93-L99

> As you can see on the image above, there are 3 files that are created as folders and not files on the npm run start script:

That screenshot appears to show only `object-cache.php` as a directory which would happen if `automattic/vip-go-mu-plugins` has not been installed before starting the container. The two other files look like proper files under `local/public`.

**Comment by nandotess** [comment]
About folders X files...

Please note the small arrow/chevron on the left:
![image](https://user-images.githubusercontent.com/804109/122438433-b7ac4180-cf68-11eb-9648-b1e8f5c15af9.png)

This is a hint these are **folders** and not **files**, such this case:
![image](https://user-images.githubusercontent.com/804109/122438484-c4c93080-cf68-11eb-93ad-c7685747ed4d.png)

This is how the **files** are displayed on my editor:
![image](https://user-images.githubusercontent.com/804109/122438697-f93cec80-cf68-11eb-8ef2-6b6a8e4514a4.png)

Thx!

**Comment by kasparsd** [comment]
@nandotess Oh, right! I was looking at these files in the previous screenshot but now I realised you're referring to the contents of `local/public/wp/...` -- those are indeed shown as directories. I first noticed these:

![122414698-55961100-cf55-11eb-9af5-79968407a79c](https://user-images.githubusercontent.com/169055/122441654-6a4ec500-cfa6-11eb-9d8e-af0076ae7a4e.png)

**Comment by kasparsd** [comment]
OK, so I've pinpointed this issue to this `jwilder/nginx-proxy` release https://github.com/nginx-proxy/nginx-proxy/releases/tag/0.9.1 which happened 3 days ago and explains why nobody notices this before.

This is also a great lesson in pinning dependency versions since `jwilder/nginx-proxy` was the only one using the latest version of the image. I'll create a pull request to fix this now, since pinning it at `0.9.0` fixed the issue for me.

**Comment by dipskakadiya** [comment]
@kasparsd 

I'm still setting issue below 

`ERROR: for eatthis_wordpress_1  Cannot start service wordpress: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/Users/dipeshkakadiya/vip/eatthis/plugins/vendor/automattic/vip-go-mu-plugins/drop-ins/object-cache/object-cache.php" to rootfs at "/var/www/html/wp-content/object-cache.php" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for wordpress  Cannot start service wordpress: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/host_mnt/Users/dipeshkakadiya/vip/eatthis/plugins/vendor/automattic/vip-go-mu-plugins/drop-ins/object-cache/object-cache.php" to rootfs at "/var/www/html/wp-content/object-cache.php" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
`

Also vip mu plugin is also not copy into to wp-content/mu-plugins.

**Comment by kasparsd** [comment]
@dipskakadiya Were you able to test this in a fresh copy of this repo clone? Alternatively, try deleting the `local/public/wp` directory and the `object-cache.php` in the root of the repository.

> Also vip mu plugin is also not copy into to wp-content/mu-plugins.

Can you please elaborate on this?

The VIP mu-plugins get mapped to `mu-plugins` only inside the containers:

https://github.com/xwp/vip-go-site/blob/56abe1f62522f01ee9de18ff0e4e63ed95ff8412/docker-compose.yml#L98

So on your local the `mu-plugins` should be an empty directory or file because it only exists in the container volume.

```
➜  vip-go-site git:(fix/nginx-proxy) ls -lah
total 792
drwxr-xr-x   32 kaspars  staff   1.0K Jun 17 20:10 .
drwxr-xr-x   16 kaspars  staff   512B Jun 17 18:57 ..
-rw-r--r--    1 kaspars  staff   300B Jun 17 18:57 .distinclude
...
drwxr-xr-x    2 kaspars  staff    64B Jun 17 19:15 mu-plugins
drwxr-xr-x  390 kaspars  staff    12K Jun 17 18:58 node_modules
-rwxr-xr-x    1 kaspars  staff     0B Jun 17 19:15 object-cache.php
...
drwxr-xr-x    4 kaspars  staff   128B Jun 17 18:57 vip-config
```

Notice how `mu-plugins` is an empty directory and `object-cache.php` is an "empty" file because that mapping relationship to `plugins/vendor/automattic/vip-go-mu-plugins` exists only inside the containers.

**Comment by dipskakadiya** [comment]
@kasparsd With Fresh Copy its works 🕺 . Thanks for help 🙏

**Comment by dipskakadiya** [comment]
@kasparsd 

Hey Dockert is running fine now, When I treid to access site it's showing database connection error 

Warning: mysqli_real_connect(): (HY000/1045): Access denied for user 'wordpress'@'172.23.0.2' (using password: YES) in /var/www/html/wp-includes/wp-db.php on line 1653 Call Stack: 0.0006 368336 1. {main}() /var/www/html/index.php:0 0.0011 368616 2. require('/var/www/html/wp-blog-header.php') /var/www/html/index.php:17 0.0017 369224 3. require_once('/var/www/html/wp-load.php') /var/www/html/wp-blog-header.php:13 0.0024 369616 4. require_once('/var/www/html/wp-config.php') /var/www/html/wp-load.php:50 0.0965 393792 5. require_once('/var/www/html/wp-settings.php') /var/www/html/wp-config.php:43 0.1135 601896 6. require_wp_db() /var/www/html/wp-settings.php:124 0.1144 603064 7. wpdb->__construct() /var/www/html/wp-includes/load.php:558 0.1144 603064 8. wpdb->db_connect() /var/www/html/wp-includes/wp-db.php:632 0.1144 604256 9. mysqli_real_connect() /var/www/html/wp-includes/wp-db.php:1653
Access denied for user 'wordpress'@'172.23.0.2' (using password: YES)

Do you have anu idea about how this fix?

**Comment by mehigh** [comment]
I had to disable gRPC fuse and let it go back to the legacy mode for Docker. 
![Screenshot 2021-06-17 at 21 38 13](https://user-images.githubusercontent.com/367593/122469238-5ebec680-cfc5-11eb-8e78-a927809254c3.png)

And I had to run `docker-compose down` and to manually delete the Volumes once that was done before running the process again with this patch and it yielded success.
