### ISSUE TITLE
DEV_URL variable that exists on .env file is not working as expected

### ISSUE THREAD

**Issue by nandotess** [xwp/vip-go-site#119]
If I rename the file `.env.example` to `.env` and updated the `DEV_URL` variable to anything different from `local.devgo.vip`, in the end of the process the custom URL provided doesn't resolve to any Docker container.

Instead the `local.devgo.vip` continue to respond via NGINX proxy container.

I saw that `docker-compose.yml` is actually considering the variable, so I'm not sure what is the route cause of this issue.

**Comment by kasparsd** [comment]
@nandotess `DEV_URL` is just a way to change the URL if the project needs it. For example, set it to `client-name.devgo.vip`. It would be the responsibly of the developer to ensure that the URL actually resolves to the `127.0.0.1` IP.

You would also need to restart the Docker containers for the changes to apply since that environment variable is used by `docker-compose` when booting the containers -- see all the environment variable references in https://github.com/xwp/vip-go-site/blob/fe7def340011c9c84d32f5fa102481ddd384dc20/docker-compose.yml

We also bundle [a DNS container](https://github.com/xwp/vip-go-site/blob/fe7def340011c9c84d32f5fa102481ddd384dc20/docker-compose.yml#L21-L28) which automatically knows where to route `DEV_URL` as long as your machine is configured to use `127.0.0.1` as one of the DNS servers. Previously it has proven to be challenging to add instructions or simple scripts to configure the custom DNS on all operating systems so we decided to default to a top-level domain that resolves to `127.0.0.1`.

**Comment by nandotess** [comment]
> @nandotess DEV_URL is just a way to change the URL if the project needs it.

@kasparsd so, this is what I was trying to do. I was trying to customize the URL for the project so I can have more than one VIP project mounted/running at the same time.

I did change the variable before anything (right after cloning the project), and at the end of all the process the URL was not working on the browser (Instead the `local.devgo.vip` continue to respond via NGINX proxy container).

This might be related to the issue https://github.com/xwp/vip-go-site/issues/116, since I was testing all this together. Not quite sure.

**Comment by kasparsd** [comment]
> I was trying to customize the URL for the project so I can have more than one VIP project mounted/running at the same time.

Thanks for the context -- really useful!

This kind of setup would be really hard because of all `nginx-proxy` containers trying to attach to port 80 on the host machine. This is "a limitation" of Docker when compared to something like Vagrant which can create a proper network interface on all operating systems.

Since `local.devgo.vip` points to `127.0.0.1`, it would always connect to any HTTP server running on your computer at port 80. Did you have any of the other containers running at the same time?

One possible solution is to adjust the exposed port number of nginx-proxy for one of the projects (to something other than 80) but that would require using that port number in the site URL which limits some of the multisite capabilities, if I'm not mistaken.

**Comment by nandotess** [comment]
Thanks, @kasparsd, that is a great explanation! So, if in this case (with Docker) I can't have more than one site running simultaneously, there is no reason I would change the URL. So that is fine and you can close this issue/ticket in case we don't want/need to customize the URL.

**Comment by kasparsd** [comment]
@nandotess One could use different URLs for each project for simplicity and developer-experience but you would always need to do `npm run stop-all` before starting the other project.
